apiVersion: v1
kind: Template
labels:
  template: redis-cluster-ephemeral
message: Redis 2 Cluster Node Ephemeral
metadata:
  annotations:
    description: Redis 2 Cluster Node Ephemeral
    iconClass: icon-mysql-database
    tags: redis-cluster
  name: redis-cluster-ephemeral
  namespace: openshift
objects:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "redis-cluster-node"
- apiVersion: v1
  kind: Service
  metadata:
    name: redis-cluster-node01
  spec:
    ports:
    - name: redis-01
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: redis-cluster-node01
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: redis-cluster-node02
  spec:
    ports:
    - name: redis-02
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: redis-cluster-node02
    sessionAffinity: None
    type: ClusterIP
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "pinpoint"
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/makentenza/ocp-pinpoint-apm.git
    strategy:
      type: "Docker"
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "centos:7"
    output:
      to:
        kind: "ImageStreamTag"
        name: "pinpoint:latest"
- apiVersion: "v1"
  kind: DeploymentConfig
  metadata:
    name: "pinpoint-apm"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: "pinpoint-apm"
      spec:
        containers:
        - name: "pinpoint"
          image: "172.30.32.89:5000/pinpoint-apm/pinpoint"
          ports:
          - containerPort: 28080
            protocol: TCP
          - containerPort: 28081
            protocol: TCP
          - containerPort: 9994
            protocol: TCP
          - containerPort: 9995
            protocol: UDP
          - containerPort: 9996
            protocol: UDP
        serviceAccount: pinpoint
        serviceAccountName: pinpoint
    replicas: 1
    triggers:
      - type: "ConfigChange"
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "pinpoint"
          from:
            kind: "ImageStreamTag"
            name: "pinpoint:latest"
    strategy:
      type: "Rolling"
    paused: false
    revisionHistoryLimit: 2
    minReadySeconds: 0
