apiVersion: v1
kind: Template
labels:
  template: redis-cluster-ephemeral
message: Redis 3 Cluster Node Ephemeral
metadata:
  annotations:
    description: Redis 3 Cluster Node Ephemeral
    iconClass: icon-mysql-database
    tags: redis-cluster
  name: redis-cluster-ephemeral
  namespace: openshift
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: redis
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "redis-cluster-node"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "redis-cluster"
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/makentenza/ocp-redis-cluster.git
    strategy:
      type: "Docker"
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "centos:7"
    output:
      to:
        kind: "ImageStreamTag"
        name: "redis-cluster-node:latest"
- apiVersion: v1
  kind: Service
  metadata:
    name: redis-cluster-service
  spec:
    ports:
    - name: redis-cluster-service
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      sname: redis-master
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1alpha1
  kind: PetSet
  metadata:
    name: redis-cluster
  spec:
    serviceName: redis-cluster-service
    replicas: 3
    template:
      metadata:
        labels:
          app: redis-master
        annotations:
          pod.alpha.kubernetes.io/initialized: "false"
      spec:
        containers:
        - name: redis-master
          imagePullPolicy: IfNotPresent
          image: "172.30.32.89:5000/redis-cluster/redis-cluster-node:latest"
          ports:
          - containerPort: 6379
            name: redis
          - containerPort: 16379
            name: redis-quorum
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_PREFIX
            value: redis-master
          - name: HEADLESS_SVC_NAME
            value: redis-master
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        serviceAccount: redis
        serviceAccountName: redis
