apiVersion: v1
kind: Template
labels:
  template: redis-cluster-ephemeral
message: Redis 2 Cluster Node Ephemeral
metadata:
  annotations:
    description: Redis 2 Cluster Node Ephemeral
    iconClass: icon-mysql-database
    tags: redis-cluster
  name: redis-cluster-ephemeral
  namespace: openshift
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: redis
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "redis-cluster-node"
- apiVersion: v1
  kind: Service
  metadata:
    name: redis-cluster-node01
  spec:
    ports:
    - name: redis-01
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: redis-cluster-node01
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: redis-cluster-node02
  spec:
    ports:
    - name: redis-02
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: redis-cluster-node02
    sessionAffinity: None
    type: ClusterIP
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "redis-cluster"
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/makentenza/ocp-redis-cluster.git
    strategy:
      type: "Docker"
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "docker.io/redis:3.2.6"
    output:
      to:
        kind: "ImageStreamTag"
        name: "redis-cluster-node:latest"
- apiVersion: "v1"
  kind: DeploymentConfig
  metadata:
    name: "redis-cluster"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: "redis-cluster"
      spec:
        containers:
        - name: "redis-cluster-node01"
          image: "172.30.32.89:5000/redis-cluster/redis-cluster-node"
          ports:
          - containerPort: 6379
            protocol: TCP
        - name: "redis-cluster-node02"
          image: "172.30.32.89:5000/redis-cluster/redis-cluster-node"
          ports:
          - containerPort: 6379
            protocol: TCP
    replicas: 1
    triggers:
      - type: "ConfigChange"
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "redis-cluster-node01"
            - "redis-cluster-node02"
          from:
            kind: "ImageStreamTag"
            name: "redis-cluster-node:latest"
    strategy:
      type: "Rolling"
    paused: false
    revisionHistoryLimit: 2
    minReadySeconds: 0
